### ISSUE TITLE
NotificationView is visible if tableView is pulled down...

### ISSUE THREAD

**Issue by Critter** [gcamp/GCDiscreetNotificationView#12]
After displaying and hiding the notificationView while loading a tableview, it is still visible if the tableview is pulled down... it just kind of hangs there...

**Comment by gcamp** [comment]
I'll refer you to that part of the read me
- _aView_ : the view that will contain the notification. The view should be able to accept subviews (will not work on a UITableView for example)

**Comment by Critter** [comment]
ah. my bad. 

cheers

**Comment by justincbeck** [comment]
This is an issue in UIScrollView (of which UITableView is a subclass) too.  The GCDiscreetNotificationView should be removed from it's superview once it has finished hiding.  Can you add a completion block that can be passed in?

**Comment by justincbeck** [comment]
I  submitted a pull request that adds a completion block property that gets executed (if it's not null) when the notification view is hidden (either animated or not).
