### ISSUE TITLE
Clickable notification view?

### ISSUE THREAD

**Issue by buraksarica** [gcamp/GCDiscreetNotificationView#13]
Hello there, I needed the notification view to be clickable, so i've made some changes for my own app. If you agree it may be useful for others, i can send you a pull request. (I haven't forked yet from github..)

**Comment by gcamp** [comment]
Yes! Feel free to make a pull request. 

However, isn't the view a little small for a touch target?

**Comment by buraksarica** [comment]
I've tested on my 3gs, and it was ok to tap. I am not sure what apple guys will say. I will make a pull request when it's ready.
