### ISSUE TITLE
Support for device rotation

### ISSUE THREAD

**Issue by yonicsurny** [gcamp/GCDiscreetNotificationView#8]
Hi, great work on this.

But I have been a little disappointed to see that the notification's frame isn't changed upon device rotation.
Would be a great thing to think about.

**Comment by gcamp** [comment]
Hi saeros,

There should not been any changes to make on device rotation, autoresizing mask will take care of that. That is, the notification should be in the view controller, not the window itself.

Guillaume

**Comment by yonicsurny** [comment]
I did place the notification on my view controller's view (like in the demo).

Maybe I'm missing something, but even if I place:

-(BOOL) shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)_interfaceOrientation
{
    return YES;
}

In your demo Xcode project, the notification's view is not correctly positioned in the controller's view.

http://i44.tinypic.com/2mo6uyw.png
http://i42.tinypic.com/309twrp.png

**Comment by andrewserff** [comment]
I've got the same issue.  Kind of annoying.

**Comment by enovav** [comment]
I also had this issue in the demo project.  A fairly easy way of fixing it seems to be to add the following code in the initWithText:showActivity: method:

```
[[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange) name:UIDeviceOrientationDidChangeNotification object:nil];
```

and then implement deviceOrientationDidChange as such:

```
- (void)deviceOrientationDidChange {
    self.center = (self.isShowing) ? self.showingCenter : self.hidingCenter;
}
```

**Comment by gcamp** [comment]
I pushed a fix on master.
